[global]

# By default, Streamlit checks if the Python watchdog module is available
# and, if not, prints a warning asking for you to install it. The watchdog
# module is not required, but highly recommended. It improves Streamlit's
# ability to detect changes to files in your filesystem.
# If you'd like to turn off this warning, set this to True.
# Default: false
disableWatchdogWarning = false

# By default, Streamlit displays a warning when a user sets both a widget
# default value in the function defining the widget and a widget value via
# the widget's key in `st.session_state`.
# If you'd like to turn off this warning, set this to True.
# Default: false
disableWidgetStateDuplicationWarning = false

# If True, will show a warning when you run a Streamlit-enabled script
# via "python my_script.py".
# Default: true
showWarningOnDirectExecution = true

# ***DEPRECATED***
# Legacy serialization has been removed. All dataframes will be serialized
# using Apache Arrow. This option will be removed on or after 2023-11-01.
# ****************
# DataFrame serialization.
# Acceptable values:
# - 'legacy' : Serialize DataFrames using Streamlit's custom format. Slow
#              but battle-tested.
# - 'arrow'  : Serialize DataFrames using Apache Arrow. Much faster and
#              versatile.
# Default: "arrow"
dataFrameSerialization = "arrow"




[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
# base =

# Primary accent color for interactive elements.
primaryColor="#F63366"

# Background color for the main content area.
backgroundColor="#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor="#F0F2F6"

# Color used for almost all text.
textColor="#262730"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font="sans serif"


